name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
jobs:
  greeting:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - id: hello
        uses: sormuras/hello-world-java-action@v1
        with:
          who-to-greet: 'ZZy'
      - run: echo random-number ${{ steps.hello.outputs.random-number }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Compiling the code..."
          sleep 10
          echo "Compile complete."

  unit-test:
    name: Unit test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          echo "Running unit tests..."
          python -m unittest calculator
          echo "Code coverage is 90%"

  lint-test:
    name: Lint test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Linting code... This will take about 10 seconds."
          sleep 10
          echo "No lint issues found."

  deploy:
    name: Deploy
    needs: [unit-test, lint-test]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying application..."
          echo "Application successfully deployed."
