name: Test
on:
  workflow_dispatch:

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install SWIG
        if: runner.os == 'macOS'
        run: brew install swig
      - name: Find tools
        run: |
          which gcc
          which python
          which swig
          which make
      - name: Print tool versions
        run: |
          gcc --version
          python --version
          ls -lh $Python_ROOT_DIR
          ls -lh $Python_ROOT_DIR/include/python3.11/Python*
          ls -lh $Python_ROOT_DIR/lib/libpython*
          swig -version
          make --version
      - name: Add system path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Print PATH
        run: echo "$PATH"
      - name: Print some paths
        run: |
          echo "${{ github.workspace }}"
          echo "${{ runner.temp }}"
          echo $HOME

  test-windows:
    defaults:
      run:
        shell: cmd
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup cl.exe and csc.exe
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          components: Microsoft.VisualStudio.Component.VC.Tools.x86.x64;Microsoft.VisualStudio.Component.Roslyn.Compiler
      - name: Find tools
        run: |
          where gcc
          where python
          where swig
          where cl
          where csc
          where mingw32-make
      - name: Print tool versions
        run: |
          gcc --version
          python --version
          dir %Python_ROOT_DIR%
          dir %Python_ROOT_DIR%\include
          swig -version
          cl
          csc
          mingw32-make --version
      - name: Add system path (bash)
        shell: bash
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Print PATH (bash)
        shell: bash
        run: echo "$PATH"
      - name: Add system path (pwsh)
        shell: pwsh
        run: |
          "$env:USERPROFILE/.local/bin2" | Out-File -FilePath $env:GITHUB_PATH -Append
      - name: Print PATH (pwsh)
        shell: pwsh
        run: $env:Path -split ';'
      - name: Compile hello_world
        run: |
          gcc -o hello_world.exe hello_world.c
          mkdir %USERPROFILE%\.local\bin
          mkdir %USERPROFILE%\.local\bin2
          copy hello_world.exe %USERPROFILE%\.local\bin\hello_world.exe
          copy hello_world.exe %USERPROFILE%\.local\bin2\hello_world2.exe
      - name: Run hello_world (bash)
        shell: bash
        run: |
          which hello_world
          which hello_world2
          hello_world
          hello_world2
      - name: Run hello_world (pwsh)
        shell: pwsh
        run: |
          where.exe hello_world
          where.exe hello_world2
          hello_world2
      - name: Print some paths (bash)
        shell: bash
        run: |
          echo "${{ github.workspace }}"
          echo "${{ runner.temp }}"
          echo $HOME
      - name: Print some paths (pwsh)
        shell: pwsh
        run: |
          echo "${{ github.workspace }}"
          echo "${{ runner.temp }}"
          echo $HOME
